### ISSUE TITLE
[1.17.1] Feature request:  Externalize block whitelist and x y z ranges

### ISSUE THREAD

**Issue by Whacker007** [kwpugh/RingOfMiner#1]
Wanted to post this request here.  Love this mod, but it doesn't work with a lot of blocks, especially the new types in the Nether like basalt, etc.  Please consider:

1.  Externalizing a whitelist of blocks the ring breaks into the mod config file,
2.  Externalizing the range at which the ring breaks blocks in the x y and z directions in the mod config file.

Thank you so much for this mod.  It's insanely useful.

**Comment by kwpugh** [comment]
Well, in the short run I will add the new basalt and Blackstone.

**Comment by kwpugh** [comment]
May look into this for current release

**Comment by kwpugh** [comment]
the range is already part of the config in recent versions.  I do not want to add blacklist/whitelist features.
